# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attached',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Documents')),
            ],
            options={
                'verbose_name_plural': 'Attachments',
                'verbose_name': 'Attachment',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('address_choice', models.CharField(choices=[('PH', 'Phone'), ('EM', 'Email')], default='PH', max_length=2, verbose_name='Address choice')),
                ('address', models.CharField(max_length=32, verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'verbose_name': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='ExamEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('start', models.DateTimeField(db_index=True, verbose_name='Start')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Exams',
                'verbose_name': 'Exam',
            },
        ),
        migrations.CreateModel(
            name='RegistrationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Start')),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deadline')),
                ('title', models.CharField(max_length=255, verbose_name='University')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True)),
                ('submitted', models.BooleanField(verbose_name='Submitted')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Cost')),
            ],
            options={
                'verbose_name_plural': 'Registrations',
                'verbose_name': 'Registration',
            },
        ),
        migrations.AddField(
            model_name='examevent',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.RegistrationEvent'),
        ),
        migrations.AddField(
            model_name='contact',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.RegistrationEvent'),
        ),
        migrations.AddField(
            model_name='attached',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.RegistrationEvent'),
        ),
    ]
