# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portables.CompanyModel', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='LayoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=128, verbose_name='Destinatario')),
                ('operation', models.CharField(max_length=256, verbose_name='Intervento')),
                ('tep', models.IntegerField(verbose_name='tonnellate equivlenti di petrolio di energia primaria')),
                ('co2', models.FloatField(blank=True, verbose_name='tonnellate/anno di minori emissioni CO2')),
                ('trees', models.IntegerField(blank=True, verbose_name='alberi salvati')),
                ('contract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portables.ContractModel')),
            ],
            options={
                'verbose_name': 'Layout',
                'verbose_name_plural': 'Layout',
            },
        ),
        migrations.CreateModel(
            name='PDFModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portables.LayoutModel', verbose_name='Local Administrative Unit')),
            ],
            options={
                'verbose_name': 'Download',
                'ordering': ['-created'],
                'verbose_name_plural': 'Downloads',
            },
        ),
    ]
