# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDFModel',
            new_name='PortableModel',
        ),
    ]
