# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portables', '0003_auto_20170610_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layoutmodel',
            options={'verbose_name': 'Layout', 'verbose_name_plural': 'Layouts'},
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='co2',
            field=models.FloatField(blank=True, verbose_name='tonne/year less emissions of CO2'),
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='operation',
            field=models.CharField(max_length=256, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='recipient',
            field=models.CharField(max_length=128, verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='tep',
            field=models.IntegerField(verbose_name='tonne of oil equivalent'),
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='trees',
            field=models.IntegerField(blank=True, verbose_name='saved trees'),
        ),
    ]
