# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-28 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Member',
        ),
    ]
