# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stocks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24)),
                ('dispatch', models.DateField()),
                ('approval', models.DateField()),
                ('years', models.PositiveIntegerField(blank=True, choices=[(8, 'Anni 8'), (5, 'Anni 5')], help_text='<a href="http://www.gse.it" target="_blank"><span class="glyphicon glyphicon-info-sign"></span></a> Anni 5 per impianti; Anni 8 per involucro.', null=True, verbose_name='Years')),
                ('stock_year', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_pct', models.FloatField(blank=True, null=True, validators=[stocks.models.valid_pct])),
                ('duty', models.CharField(blank=True, max_length=24)),
                ('protocol', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_year_customer', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
