# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20170610_0117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApprovedCertification',
            new_name='Approved',
        ),
        migrations.RenameModel(
            old_name='DispatchedCertification',
            new_name='Dispatched',
        ),
        migrations.RenameField(
            model_name='approved',
            old_name='dispatched_certification',
            new_name='dispatched',
        ),
    ]
