# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20170610_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approved',
            options={'verbose_name': 'Approved certification', 'verbose_name_plural': 'Approved certifications'},
        ),
        migrations.AlterModelOptions(
            name='dispatched',
            options={'verbose_name': 'Dispatched certification', 'verbose_name_plural': 'Dispatched certifications'},
        ),
    ]
