# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 19:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinAmbiguous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(help_text='JSON values: Ex. [1, 2]', max_length=64, unique=True, verbose_name='Coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Binder content')),
                ('color', models.CharField(blank=True, help_text='Hex value.', max_length=6, verbose_name='Color')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Binders',
                'verbose_name': 'Binder',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField(blank=True, null=True, verbose_name='Column')),
                ('row', models.IntegerField(blank=True, null=True, verbose_name='Row')),
            ],
            options={
                'verbose_name_plural': 'Containers',
                'verbose_name': 'Container',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(help_text='Customer code must not be confused with user code!', null=True, unique=True, verbose_name='Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'verbose_name': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the shelf.', max_length=64, unique=True, verbose_name='Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('cols', models.PositiveIntegerField(blank=True, help_text='The number of cols', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Columns')),
                ('rows', models.PositiveIntegerField(blank=True, help_text='The number of rows', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rows')),
                ('nums', models.PositiveIntegerField(blank=True, help_text='The number of containers', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Containers')),
            ],
            options={
                'verbose_name_plural': 'Shelves',
                'verbose_name': 'Shelf',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='docs', verbose_name='File CSV')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.Shelf'),
        ),
        migrations.AddField(
            model_name='binder',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelves.Container'),
        ),
        migrations.AddField(
            model_name='binder',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelves.Customer'),
        ),
    ]
