# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-13 14:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField(blank=True, verbose_name='Binder content')),
                ('color', models.CharField(blank=True, help_text='Hex value.', max_length=6, verbose_name='Color')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Binder',
                'verbose_name_plural': 'Binders',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField(blank=True, null=True, verbose_name='Column')),
                ('row', models.IntegerField(blank=True, null=True, verbose_name='Row')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Name')),
                ('code', models.SlugField(help_text='The customer code must not be confused with the customer id or the user id!', max_length=16, verbose_name='Code')),
                ('note', models.TextField(blank=True, max_length=128, verbose_name='Note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the shelf.', max_length=64, unique=True, verbose_name='Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('cols', models.PositiveIntegerField(blank=True, help_text='The number of cols', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Columns')),
                ('rows', models.PositiveIntegerField(blank=True, help_text='The number of rows', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rows')),
                ('nums', models.PositiveIntegerField(blank=True, help_text='The number of containers', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Containers number')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='docs', verbose_name='File CSV')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.Shelf'),
        ),
        migrations.AddField(
            model_name='binder',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.Container'),
        ),
        migrations.AddField(
            model_name='binder',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelves.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('code', 'author')]),
        ),
    ]
