# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(help_text="Please, use 0 if you can't assign coordinates.")),
                ('col', models.IntegerField(help_text="Please, use 0 if you can't assign coordinates.")),
                ('coordinate', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BinAmbiguous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(help_text='JSON values: Ex. [1, 2]', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.IntegerField()),
                ('nome', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='docs')),
            ],
        ),
        migrations.AddField(
            model_name='binder',
            name='biography',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='shelves.Customer'),
        ),
        migrations.AddField(
            model_name='binder',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.Shelf'),
        ),
        migrations.AddField(
            model_name='binder',
            name='shelf_bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.Bin'),
        ),
    ]
