# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-07 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binder',
            name='col',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='binder',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
