# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField(verbose_name='Column')),
                ('row', models.IntegerField(verbose_name='Row')),
                ('coordinate', models.CharField(blank=True, max_length=64, verbose_name='Coordinate')),
            ],
            options={
                'verbose_name_plural': 'Bins',
                'verbose_name': 'Bin',
            },
        ),
        migrations.CreateModel(
            name='RegularShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Shelf name')),
                ('cols', models.IntegerField(help_text='Number of cols', verbose_name='Columns')),
                ('rows', models.IntegerField(help_text='Number of rows', verbose_name='Rows')),
            ],
            options={
                'verbose_name_plural': 'Shelves',
                'verbose_name': 'Shelf',
            },
        ),
        migrations.AlterModelOptions(
            name='binder',
            options={'verbose_name': 'Binder', 'verbose_name_plural': 'Binders'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RemoveField(
            model_name='binder',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='binder',
            name='shelf_bin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='codice',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nome',
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.IntegerField(help_text='Customer code must not be confused with user code!', null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='binambiguous',
            name='coordinate',
            field=models.CharField(help_text='JSON values: Ex. [1, 2]', max_length=64, unique=True, verbose_name='Coordinate'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='csv_file',
            field=models.FileField(upload_to='docs', verbose_name='File CSV'),
        ),
        migrations.DeleteModel(
            name='Bin',
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
        migrations.AddField(
            model_name='regularbin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.RegularShelf'),
        ),
        migrations.AddField(
            model_name='binder',
            name='regular_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelves.RegularBin'),
        ),
    ]
