# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-14 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='slug',
            field=models.SlugField(default='a', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together=set([('slug', 'author')]),
        ),
    ]
