# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-14 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_auto_20180114_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(help_text='A name for the shelf.', max_length=64, verbose_name='Name'),
        ),
    ]
