# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-07 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_auto_20180207_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='uuid',
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
