# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-15 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelves', '0003_auto_20180114_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='slug',
            new_name='code',
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together=set([('code', 'author')]),
        ),
    ]
