# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-15 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_auto_20180207_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attached',
            new_name='Attachment',
        ),
    ]
