# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_auto_20170702_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binder',
            name='biography',
        ),
        migrations.AddField(
            model_name='binder',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='shelves.Customer'),
            preserve_default=False,
        ),
    ]
