# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-29 03:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_auto_20171201_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='', help_text='The customer code must not be confused with the customer id or the user id!', max_length=16, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='nums',
            field=models.PositiveIntegerField(blank=True, help_text='The number of containers', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Containers number'),
        ),
    ]
