# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-31 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_auto_20171229_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='created',
            field=models.DateField(auto_now_add=True, default='2017-01-01'),
            preserve_default=False,
        ),
    ]
