# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_auto_20170705_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularbin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularbins', to='shelves.RegularShelf'),
        ),
    ]
