# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-08 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0006_upload_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BinAmbiguous',
        ),
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, max_length=128, verbose_name='Note'),
        ),
    ]
