# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0008_auto_20170705_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegularShelf',
            new_name='Shelf',
        ),
    ]
