# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0009_auto_20170705_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binder',
            old_name='regular_bin',
            new_name='bin',
        ),
    ]
