# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0011_binder_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='binder',
            name='content',
            field=models.TextField(blank=True, verbose_name='Binder content'),
        ),
        migrations.AddField(
            model_name='binder',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Binder name'),
        ),
        migrations.AddField(
            model_name='binder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shelf',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='numb',
            field=models.PositiveIntegerField(blank=True, help_text='The number of bins', null=True, verbose_name='Bins'),
        ),
        migrations.AlterField(
            model_name='binder',
            name='color',
            field=models.CharField(blank=True, help_text='Hex value.', max_length=6, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='binder',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='shelves.Customer'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='cols',
            field=models.IntegerField(blank=True, help_text='The number of cols', null=True, verbose_name='Columns'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(default=1, help_text='A name for the shelf.', max_length=64, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelf',
            name='rows',
            field=models.IntegerField(blank=True, help_text='The number of rows', null=True, verbose_name='Rows'),
        ),
    ]
