# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0012_auto_20170706_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='num',
            field=models.IntegerField(default=1, verbose_name='Number'),
            preserve_default=False,
        ),
    ]
