# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0013_bin_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Number')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.Shelf')),
            ],
            options={
                'verbose_name_plural': 'Containers',
                'verbose_name': 'Container',
            },
        ),
        migrations.RemoveField(
            model_name='bin',
            name='num',
        ),
    ]
