# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0014_auto_20170706_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='numb',
            field=models.PositiveIntegerField(blank=True, help_text='The number of containers', null=True, verbose_name='Containers'),
        ),
    ]
