# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0017_auto_20170706_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binder',
            name='board',
        ),
        migrations.AddField(
            model_name='binder',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelves.Container'),
        ),
    ]
