# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0018_auto_20170706_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(help_text='A name for the shelf.', max_length=64, verbose_name='Name'),
        ),
    ]
