# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0020_auto_20170707_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='container',
            name='num',
        ),
        migrations.AlterField(
            model_name='binder',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelves.Customer'),
        ),
        migrations.AlterField(
            model_name='board',
            name='container',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shelves.Container'),
        ),
    ]
